---
- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Set default incoming policy
  community.general.ufw:
    direction: incoming
    policy: "{{ firewall_default_incoming }}"

- name: Set default outgoing policy
  community.general.ufw:
    direction: outgoing
    policy: "{{ firewall_default_outgoing }}"

- name: Allow firewall rules
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.protocol | default('tcp') }}"
  loop: "{{ firewall_rules }}"

- name: Enable firewall
  community.general.ufw:
    state: enabled
  when: firewall_enabled
  