---
- name: Manage users
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | default(omit) }}"
    append: "{{ item.append | default(true) }}"
    create_home: "{{ item.create_home | default(true) }}"
    password: "{{ item.password | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
  loop: "{{ users }}"
