---
- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Enable fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
  when: fail2ban_enabled
