---
- name: Manage services
  ansible.builtin.systemd:
    name: "{{ item.name }}"
    state: "{{ item.state | default('started') }}"
    enabled: "{{ item.enabled | default(true) }}"
  loop: "{{ services }}"
