---
- name: Manage services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: "{{ services_state | default('started') }}"
    enabled: "{{ item.enabled | default(true) }}"
  loop: "{{ services_list }}"
